basePath: /
definitions:
  models.Ticket:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      kermesse_id:
        description: Référence vers la Kermesse
        type: integer
      purchased_at:
        description: Date d'achat des tickets
        type: string
      student_id:
        description: Référence vers un Student
        type: integer
      ticket_number:
        description: Numéro unique du ticket
        type: string
      tombola_id:
        description: Référence vers la Tombola
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: Swagger API for the Kiwi Collective project.
  title: Kiwi Collective API
  version: "1.0"
paths:
  /tickets:
    post:
      consumes:
      - application/json
      description: Crée un billet de tombola pour un étudiant.
      parameters:
      - description: Ticket à créer
        in: body
        name: ticket
        required: true
        schema:
          $ref: '#/definitions/models.Ticket'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Ticket'
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Bad request
          schema:
            type: string
      summary: Créer un nouveau ticket
      tags:
      - Tickets
swagger: "2.0"
