#version: "3.7"
services:
  database:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: challenge_rattrapage
      POSTGRES_DB: postgres_challenge
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - database
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      GO_ENV: production  # Assurez-vous de le changer pour production lors du déploiement
      
