// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-3mVcCL8UYP4oAEnGfUAOa8vc5pdrxk',
    appId: '1:377950971319:web:7e294c6be0e6afa09bb432',
    messagingSenderId: '377950971319',
    projectId: 'kermesse-land',
    authDomain: 'kermesse-land.firebaseapp.com',
    storageBucket: 'kermesse-land.appspot.com',
    measurementId: 'G-1L8HL5Y8J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_cr_RO4TDBBCXUBa3f71gs7xZAtD_v4',
    appId: '1:377950971319:android:52ff1b7b19f756639bb432',
    messagingSenderId: '377950971319',
    projectId: 'kermesse-land',
    storageBucket: 'kermesse-land.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-5v84iilymGQcl8VnsGhoRL4XVivdIg',
    appId: '1:377950971319:ios:e34d9e1ab098fe489bb432',
    messagingSenderId: '377950971319',
    projectId: 'kermesse-land',
    storageBucket: 'kermesse-land.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-5v84iilymGQcl8VnsGhoRL4XVivdIg',
    appId: '1:377950971319:ios:e34d9e1ab098fe489bb432',
    messagingSenderId: '377950971319',
    projectId: 'kermesse-land',
    storageBucket: 'kermesse-land.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx-3mVcCL8UYP4oAEnGfUAOa8vc5pdrxk',
    appId: '1:377950971319:web:1a708b9089b8ef449bb432',
    messagingSenderId: '377950971319',
    projectId: 'kermesse-land',
    authDomain: 'kermesse-land.firebaseapp.com',
    storageBucket: 'kermesse-land.appspot.com',
    measurementId: 'G-2K5K4RVK75',
  );

}